version: '3'

services:
  prometheus:
    image: prom/prometheus:v1.7.1
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    ports:
      - 9090:9090
    # command: -config.file=/etc/prometheus/prometheus.yml

  docker:
    image: docker:17.07-dind
    privileged: true
    restart: unless-stopped
    volumes:
      - docker:/var/lib/docker
    ports:
      - 8500:8500
      - 2375:2375

volumes:
  docker:
  prometheus:

