version: '3'
services:
  consul:
    image: gliderlabs/consul-server 
    restart: unless-stopped
    ports:
      - 8500:8500
    command: -bootstrap 
    # command: -server -bootstrap -advertise docker
    # command: -server -bootstrap -advertise 172.17.0.1
    # -advertise ${HOST_IP_ADDRESS}

  registrator:
    image: gliderlabs/registrator 
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock 
    command: consul://consul:8500
    # command: -ip ${HOST_IP_ADDRESS} consul://consul:8500
    # command: -ip docker consul://consul:8500

  pushgateway:
    image: prom/pushgateway:v0.4.0
    restart: unless-stopped
    environment:
      - SERVICE_TAGS=monitored
    ports:
      - 9091

