version: '3'
services:
  consul:
    image: gliderlabs/consul-server 
    restart: unless-stopped
    ports:
      - 8500:8500
    command: -bootstrap 

  registrator:
    image: gliderlabs/registrator 
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock 
    command: consul://consul:8500

  pushgateway:
    image: prom/pushgateway:v0.4.0
    restart: unless-stopped
    environment:
      # - SERVICE_TAGS=monitored
      - SERVICE_NAME=bss_bss
      - SERVICE_TAGS=monitored,path=metrics
    ports:
      - 9091

