global:
  scrape_interval: 20s
  scrape_timeout: 5s # How long until a scrape request times out.  default = 10s 
  evaluation_interval: 1m # How frequently to evaluate rules.  default = 1m 

scrape_configs:
  - job_name: dummy  # This is a default value, it is mandatory.
    honor_labels: true
    file_sd_configs:
      - files:
        - /prometheus_configuration/targets/*.yml
        - /prometheus_configuration/targets/*.json
        refresh_interval: 5s
  - job_name: scrape_15s
    honor_labels: true
    scrape_interval: 15s
    scrape_timeout: 5s
    file_sd_configs:
      - files:
        - /prometheus_configuration/targets/15s/*.yml
        - /prometheus_configuration/targets/15s/*.json
        refresh_interval: 5s
  - job_name: scrape_10s
    honor_labels: true
    scrape_interval: 10s
    scrape_timeout: 5s
    file_sd_configs:
      - files:
        - /prometheus_configuration/targets/10s/*.yml
        - /prometheus_configuration/targets/10s/*.json
        refresh_interval: 5s
  - job_name: scrape_5s
    honor_labels: true
    scrape_interval: 5s
    scrape_timeout: 5s
    file_sd_configs:
      - files:
        - /prometheus_configuration/targets/5s/*.yml
        - /prometheus_configuration/targets/5s/*.json
        refresh_interval: 5s

