simplesource:
   image: nasoym/bss_extended
   volumes:
     - ./simple:/handlers
   ports: 
     - 8080:8080

es:
   image: elasticsearch
   ports: 
     - 9200:9200

grafana:
   image: grafana/grafana:3.1.1
   ports: 
     - 3000:3000
   environment:
     - GF_DASHBOARDS_JSON_ENABLED=true
     - GF_AUTH_ANONYMOUS_ENABLED=true
     - GF_INSTALL_PLUGINS=grafana-simple-json-datasource
   links:
     - es
     - simplesource

