#!/bin/bash

# curl "http://localhost:9200/test/_search"| jq .
# curl -XPOST -d '{"fields":["@timestamp","value"],"query":{"match_all":{}}}' "http://localhost:9200/test/_search"| jq .

curl -s "http://localhost:9200/test/_search" 

