#!/bin/bash

docker-compose up -d

curl -s "http://localhost:7379/SET/foo/bar"
curl -s "http://localhost:7379/GET/foo"
curl -s "http://localhost:7379/GET/foo"
curl -s "http://localhost:7379/GET/foo"

