FROM ubuntu:19.04
MAINTAINER Sinan Goo

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update; apt-get install -y cron prometheus-node-exporter

# Add crontab file in the cron directory
ADD crontab.txt /etc/cron.d/crontab.txt

# Give execution rights on the cron job
RUN chmod 0644 /etc/cron.d/crontab.txt

# Apply cron job
RUN crontab /etc/cron.d/crontab.txt

# Create the log file to be able to run tail
RUN touch /var/log/cron.log

RUN mkdir -p /etc/node_exporter_textfiles

EXPOSE 9100

CMD cron && prometheus-node-exporter --collector.textfile.directory /etc/node_exporter_textfiles
# CMD cron -f

