global:
  scrape_interval: 1s 
  scrape_timeout: 1s 
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'cron'
    honor_labels: true
    static_configs:
      - targets: ['cron_host:9100']
  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

