global:
  scrape_interval: 5s 

rule_files:
  - /etc/prometheus/alerts/push_alert.rules

scrape_configs:
  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

