storage:
  image: prom/prometheus:0.20.0
  volumes:
    - /etc/prometheus
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    - ./push_alert.rules:/etc/prometheus/alerts/push_alert.rules
  command: "true"

pushgateway:
  image: prom/pushgateway:0.3.0
  ports:
    - 9091:9091

alertmanager:
  image: prom/alertmanager:v0.4.2
  ports:
    - 9093:9093
  volumes:
    - ./alertmanager_config.yml:/etc/alertmanager/config.yml

prometheus:
  image: prom/prometheus:0.20.0
  volumes_from:
    - storage
  volumes:
      - ./push_alert.rules:/etc/prometheus/alerts/push_alert.rules
      # - ./prometheus.yml:/etc/prometheus/prometheus.yml
  ports:
    - 9090:9090
  command: -config.file=/etc/prometheus/prometheus.yml -storage.local.path=/prometheus -web.console.libraries=/etc/prometheus/console_libraries -web.console.templates=/etc/prometheus/consoles -alertmanager.url=http://alertmanager:9093 
  links:
    - pushgateway
    - alertmanager


