
rule_files:
  - /etc/prometheus/alerts/push_alert.rules

scrape_configs:
  - job_name: 'pushgateway'
    scrape_interval: 5s
    scrape_timeout: 4s
    static_configs:
      - targets: ['pushgateway:9091']

