#!/bin/bash


QUERY="$@"
: ${QUERY:="bla"}

QUERY="$(echo "$QUERY" | python -c "import urllib, sys; print urllib.quote(sys.stdin.read())" )"

curl -s "http://localhost:9090/api/v1/query?query=${QUERY}"  \
  | jq .

