#!/bin/bash

docker-compose up -d


# open -a "Google Chrome" "http://localhost:9090/graph#%5B%7B%22range_input%22%3A%221h%22%2C%22end_input%22%3A%22%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3A%22%22%2C%22expr%22%3A%22foo%22%2C%22tab%22%3A0%7D%5D"
# open -a "Google Chrome" "http://localhost:9090/alerts"
# open -a "Google Chrome" "http://localhost:9093/#/alerts"

# for i in {1..20}; do 
#   curl -s "http://localhost:9091" >/dev/null && break
#   sleep 1
# done
# curl -s "http://localhost:9091" >/dev/null || { echo "server did not respond!" >&2; exit 1;}
#
# sleep 5
#
# ./push_metric 12

