datasource:
    image: shell_goexpose
    ports:
      - 9900:9900
    volumes:
      - ./goexpose.json:/scripts/goexpose_config.json
      - ./files:/files
    command: "goexpose -logtostderr --config /scripts/goexpose_config.json"

grafana:
   image: grafana/grafana:3.1.1
   ports: 
     - 3000:3000
   environment:
     - GF_DASHBOARDS_JSON_ENABLED=true
     - GF_AUTH_ANONYMOUS_ENABLED=true
     - GF_INSTALL_PLUGINS=grafana-simple-json-datasource
     # - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,mtanda-heatmap-epoch-panel,mtanda-histogram-panel,grafana-piechart-panel
   links:
     - datasource


