global:
  resolve_timeout: 10s 

# The root route on which each incoming alert enters.
route:
  receiver: slow-receiver

  # # The child route trees. Not used at the moment.
  # routes:
      # resolve_timeout: 30s
  routes:
    - match:
        slow: "true"
      receiver: slow-receiver 
    - match:
        fast: "true"
      receiver: fast-receiver 

receivers:
- name: slow-receiver

- name: fast-receiver

