#!/bin/bash

# echo "bla {name=\"eins\",host=\"a\"} 1" | curl -s -XPUT --data-binary @- "http://localhost:9091/metrics/job/bla"
# echo "bla {name=\"zwei\",host=\"b\"} 10" | curl -s -XPUT --data-binary @- "http://localhost:9091/metrics/job/bla"
# echo "bla {name=\"drei\",host=\"c\"} 20" | curl -s -XPUT --data-binary @- "http://localhost:9091/metrics/job/bla"
# echo "bla {name=\"vier\",host=\"d\"} 15" | curl -s -XPUT --data-binary @- "http://localhost:9091/metrics/job/bla"
# echo "bla {name=\"fuenf\",host=\"e\"} 1" | curl -s -XPUT --data-binary @- "http://localhost:9091/metrics/job/bla"


echo "bar 10" | curl -s -XPUT --data-binary @- "http://localhost:9091/metrics/job/bar/name/one"
echo "bar 15" | curl -s -XPUT --data-binary @- "http://localhost:9091/metrics/job/bar/name/two"
echo "bar 20" | curl -s -XPUT --data-binary @- "http://localhost:9091/metrics/job/bar/name/three"
echo "bar 9" | curl -s -XPUT --data-binary @- "http://localhost:9091/metrics/job/bar/name/four"
echo "bar 1" | curl -s -XPUT --data-binary @- "http://localhost:9091/metrics/job/bar/name/five"



