#!/bin/bash
#
# echo "[
#   {
#     \"columns\": [
#       { \"text\": \"_id\", \"type\":\"text\" }
#     ],
#     \"rows\": [ {\"_id\":\"AVkHj_qoD5gg4vbS3Fri\",\"_type\":\"log\",\"_index\":\"logs-2016.12.16\",\"@message\":\"Deployed website\",\"@timestamp\":[1481890593445],\"tags\":[\"deploy\",\"website-01\"],\"description\":\"Torkel deployed website\",\"coordinates\":{\"latitude\":12,\"longitude\":121,\"level\":{\"depth\":3,\"coolnes\":\"very\"}},\"long\":\"asdsaa asdas dasdas dasdasdas asdaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa asdasdasdasdasdasdas asd\",\"unescaped-content\":\"breaking <br /> the <br /> row\"} ], 
#     \"type\": \"table\"
#   }
# ]
# "

echo "[{
\"columns\": [
  { \"text\": \"name\", \"type\":\"text\" },
  { \"text\": \"code\", \"type\":\"number\", \"sort\":true, \"desc\":false }
],
\"rows\": [[\"foo\",400],[\"bar\",500]], 
\"type\": \"table\"}]
"

# echo "{
#   \"took\": 4,
#   \"timed_out\": false,
#   \"_shards\": {
#     \"total\": 5,
#     \"successful\": 5,
#     \"failed\": 0
#   },
#   \"hits\": {
#     \"total\": 3,
#     \"max_score\": 1,
#     \"hits\": [
#       {
#         \"_index\": \"test\",
#         \"_type\": \"test\",
#         \"_id\": \"AVlz_0MkCucNJerjWQQr\",
#         \"_score\": 1,
#         \"_source\": {
#           \"value\": 2,
#           \"@timestamp\": [
#             1483709825814
#           ]
#         }
#       },
#       {
#         \"_index\": \"test\",
#         \"_type\": \"test\",
#         \"_id\": \"AVlz_zZ9CucNJerjWQQp\",
#         \"_score\": 1,
#         \"_source\": {
#           \"value\": 2,
#           \"@timestamp\": [
#             1483709822202
#           ]
#         }
#       },
#       {
#         \"_index\": \"test\",
#         \"_type\": \"test\",
#         \"_id\": \"AVlz_z6VCucNJerjWQQq\",
#         \"_score\": 1,
#         \"_source\": {
#           \"value\": 3,
#           \"@timestamp\": [
#             1483709824646
#           ]
#         }
#       }
#     ]
#   }
# }
# "
