FROM alpine:3.6

# RUN apk update ; apk add parallel curl
RUN apk update ; apk add bash parallel 

# CMD ["sed","s/^/AA/g"]
# CMD ["ls","-la","/home/host"]
# CMD ["find . -mindepth 2 -type f -name "*.rules" | parallel 'cat {} > $(echo "{}" | sed -e "s/^\.\///g" -e "s/\//_/g")']
# ENTRYPOINT ["seq","1","4"]
# ENTRYPOINT ["sh","-c","seq 1 4 | sed 's/^/---/g'"]
# CMD ["bash","-c","seq 1 4 | sed 's/^/---/g'"]
WORKDIR /home/host

# CMD ["bash","-c","find . -mindepth 2 -type f -name \"*.rules\" | parallel 'cat {} > $(echo \"{}\" | sed -e \"s/^\.\///g\" -e \"s/\//_/g\")'"]
CMD ["bash","-c","find . -mindepth 2 -type f -name \"*.rules\" | parallel 'cat {} > $(echo {} | sed -e \"s/^\\.\\///g\" -e \"s/\\//_/g\")'"]

# CMD ["seq","1","4","|","cat"]


