#!/bin/bash

: ${GRAFANA_SERVER:="http://localhost:3000"}

curl -X POST -H 'Content-Type: application/json;charset=UTF-8' --user admin:admin \
--data-binary "{\
\"name\": \"one\",\
\"type\": \"grafana-simple-json-datasource\",\
\"access\": \"proxy\",\
\"url\": \"http://datasource:8080/one\",\
\"basicAuth\": false\
}" \
"${GRAFANA_SERVER}/api/datasources"

curl -X POST -H 'Content-Type: application/json;charset=UTF-8' --user admin:admin \
--data-binary "{\
\"name\": \"two\",\
\"type\": \"grafana-simple-json-datasource\",\
\"access\": \"proxy\",\
\"url\": \"http://datasource:8080/two\",\
\"basicAuth\": false\
}" \
"${GRAFANA_SERVER}/api/datasources"


