scrape_configs:
  - job_name: 'prometheus'

    scrape_interval: 5s
    scrape_timeout: 4s

    target_groups:
      - targets: ['localhost:9090']

  # - job_name: 'host'
  #   static_configs:
  #     - targets: ['node_exporter:9100']
  #       labels:
  #         stage: 'stage_exp'
  #         tier:  'tier_exp'
  #
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis_exporter:9121']
  #       labels:
  #         stage: 'stage_exp'
  #         tier:  'tier_redis'

