global:
  resolve_timeout: 1m
  group_wait: 1s
  group_interval: 1s
  repeat_interval: 30s

route:
  receiver: empty-receiver

  routes:
    - match:
        silent_alert: "true"
      receiver: silent-receiver 

receivers:
- name: empty-receiver
- name: silent-receiver

