#!/bin/bash

watch -t -n 1 "./prom_query \
  | gnuplot -e \"\
set terminal dumb $(tput cols),$(tput lines);\
set xdata time;\
set yrange [0:30];\
set nokey;\
set tmargin 0;\
set bmargin 0;\
set rmargin 0;\
unset xtics;\
set ytics nomirror scale 0;\
set timefmt '%s';\
plot '-' using 1:2 w l;\
\" "

# set rmargin 0;\
# set bmargin 0;\
# set terminal dumb $(tput cols),$(( $(tput lines) + 2 ));\

