#!/bin/bash

watch -t -n 1 "./prom_query | gnuplot -e \"set terminal dumb $(tput cols),$(( $(tput lines) + 2 )); set xdata time; set notitle; set nokey; set tics nomirror scale 0 ;set timefmt '%s';unset xtics;plot '-' using 1:2 w l notitle;\" "

