#!/bin/bash

while getopts ":-:" OPTIONS; do 
  unset VALUE
  if [[ ${!OPTIND} =~ ^-$ ]] || [[ ${!OPTIND} =~ ^[^-] ]];then
    VALUE=${!OPTIND}; OPTIND=$((OPTIND+1))
  fi
  case $OPTIONS in
  *) case "${OPTARG}" in
      d|duration) DURATION=$VALUE ;;
      m|metric) METRIC=$VALUE ;;
esac; esac; done; shift $((OPTIND-1))

: ${DURATION="5 minutes"}
: ${METRIC="foo"}

curl -s \
  "http://localhost:9090/api/v1/query_range?\
query=$METRIC\
&start=$(gdate -d "- $DURATION" +%s)\
&end=$(gdate +%s)\
&step=1s\
" \
| jq -r -c '.data.result[0].values|map("\(.[0]) \(.[1])")[]'

